config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :artworks, only: [:index, :create, :new, :show] do
    resources :comments, except: [:show, :destroy]
    resources :saved_artworks, only: [:new, :create]
  end

  resources :viewing_locations, only: [:show] do
    resources :favorites, only: [:create]
  end

  resources :comments, only: [:destroy, :edit, :update]
  resources :favorites, only: [:index, :destroy]
  resources :users, only: [:show]
  get "/collections/:tag", to: "saved_artworks#show", as: "collection"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :saved_artworks, dependent: :destroy

  after_create :add_favorites_to_user

  def favorited?(viewing_location)
    favorites.find_by(viewing_location_id: viewing_location.id)
  end

  def saved?(artwork)
    saved_artworks.find_by(artwork_id: artwork.id)
  end

  def saved_artworks_for(tag)
    saved_artworks.where(tag: tag).map(&:artwork)
  end

  private

  def add_favorites_to_user
    favorites = SavedArtwork.new(user_id: self.id, tag: "Favorites")
    favorites.save(validate: false)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @favorites = current_user.favorites
    @saved_artworks = current_user.saved_artworks
    @tags = get_tags
  end

  private

  def get_tags
    current_user.saved_artworks.pluck(:tag).uniq
  end
end

app/views/users/show.html.erb
<div class="container">
  <div class="user-content">
    <h3><%= current_user.username %></h3>
    <p><%= current_user.email %></p>

    <div class="top-and-bottom-border"></div>
    <div class="open-tab-buttons">
      <button class="activity-btn active" id="btn-left"> Collections </button>
      <button class="activity-btn" id="btn-right" > Saved Galleries </button>
    </div>

    <div id="content-left">
      <div class="collections mt-3">
        <% @tags.each do |tag| %>
          <%= link_to collection_path(tag) do %>
            <div class="collection-thumb d-flex">
              <% if current_user.saved_artworks_for(tag).last %>
                <div class="collection-image"><%= cl_image_tag current_user.saved_artworks_for(tag).last.photo, alt: "#" %></div>
              <% else %>
                <div class="collection-image"><i class="fas fa-palette"></i></div>
              <% end %>
              <div class="collection-tag-link">
                <p><%= tag %></p>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>

    <div id="content-right">
      <div class="collections mt-3">
        <% current_user.favorites.each do |favorite| %>
          <%= link_to viewing_location_path(favorite.viewing_location) do %>
            <div class="collection-thumb d-flex">
              <% if current_user.favorites %>
                <div class="collection-image"><%= cl_image_tag favorite.viewing_location.photo, alt: "#" %></div>
              <% end %>
              <div class="collection-tag-link">
                <p><%= favorite.viewing_location.name %></p>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>

  </div>
</div>