config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :artworks, only: [:index, :create, :new, :show] do
    resources :comments, except: [:show, :destroy]
    resources :saved_artworks, only: [:new, :create]
  end

  resources :viewing_locations, only: [:show] do
    resources :favorites, only: [:create]
  end

  resources :comments, only: [:destroy, :edit, :update]
  resources :favorites, only: [:index, :destroy]
  resources :users, only: [:show]
  get "/collections/:tag", to: "saved_artworks#show", as: "collection"
end

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1509114397022-ed747cca3f65?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=975&q=80);">
  <div class="container">

    <h1><strong>Discover the world of art</strong></h1>
    <br>
    <h3>Explore artwork and galleries wherever you are</h3>
    <%= render 'shared/search' %>
  </div>
</div>

app/views/shared/_button.html.erb
<a class="btn-flat btn-flat" href="#">Button</a>

app/views/shared/_comments.html.erb
<div class="container">

<!-- <h3>Comments</h3> -->

<% @artwork.comments.each do |comment| %>
  <div class="comment-flex">
    <div class="name-comment">
      <p><strong><%= comment.user.username %></strong>
      <br> <%= comment.content %></p>
    </div>
    <div class="edit-delete">
      <%= link_to "<i class=\"fas fa-pencil-alt\"></i>".html_safe, edit_artwork_comment_path(@artwork.id, comment.id) %>
      <%= link_to "<i class=\"far fa-trash-alt\"></i>".html_safe, comment_path(comment.id), method: :delete, data: {confirm: "Are you sure?"} %>
    </div>
  </div>
<% end %>

<div class="comment-input">
<%= simple_form_for [ @artwork, @comment] do |f| %>
  <%= f.error_notification %>
  <%= f.input :content, label: false, placeholder: "New comment..." %>
   <%= f.button :submit, class: "btn-flat new-comment-btn" %>
<% end %>
</div>
</div>

app/views/shared/_details-artwork-banner.html.erb
<%= cl_image_tag artwork.photo, alt: "#" %>

app/views/shared/_details-artwork.html.erb
<div class="container">
  <div class="details-head">
    <div class="headings">
      <div class="art-title"><%= artwork.title %></div>
  <!--   date_of_creation:
    medium:
    category: -->
    <div class="artist-name"><%= artwork.artist.name %></div>
  </div>
  <div class="fave-save">
    <% if current_user.saved?(artwork) %>
    <div class="fave-save-icon"><i class="fas fa-heart" style="color: #F85961"></i></div>
    <% else %>
    <div class="fave-save-icon"><i class="far fa-heart" style="color: black"></i></div>
    <% end %>
  </div>
  </div>

  <div class="details-body">
    <div class="description">

      <div class="top-and-bottom-border">
        <div class="font-grey-to-black">
          <p><strong>Gallery</strong></p>
        </div>
        <div class="flex-justify-space-between">
          <div class="flex">
          <div class="collection-image"><%= cl_image_tag artwork.viewing_location.photo, alt: "#" %></div>
          <p><%= artwork.viewing_location.name %></p>
          </div>
          <%= link_to "Gallery Info", viewing_location_path(artwork.viewing_location), class: "btn-flat-small" %>
        </div>
      </div>

      <div class="top-and-bottom-border">
        <div class="font-grey-to-black ">
          <p><strong>Artist details</strong></p>
        </div>
        <p> <%= artwork.artist.bio.truncate_words(24) %> <i> read more</i></p>
      </div>

      <div class="top-and-bottom-border">
        <div class="font-grey-to-black ">
          <p><strong>Artwork details</strong></p>
        </div>
        <p><strong> Date of creation </strong></p>
        <p> <%= artwork.date_of_creation %> </p>
        <br>
        <p><strong> Medium </strong></p>
        <p> <%= artwork.medium %> </p>
        <br>
        <p><strong> Category </strong></p>
        <p> <%= artwork.category %> </p>
      </div>

      <div class="top-and-bottom-border">
        <div class="font-grey-to-black ">
          <% if artwork.artist.artworks.count > 1%>
          <p><strong>Work by <%= artwork.artist.name %></strong></p>
        </div>
        <div class="other-art-by-artist">
          <% artwork.artist.artworks.each do |artwork| %>
          <%= link_to artwork_path(artwork) do %>
          <div class="artwork-thumbnail"><%= cl_image_tag artwork.photo %></div>
          <% end %>
          <% end %>
        </div>
        <% end %>
      </div>
    </div>


    <!-- THIS IS THE MODAL -->

  </div>
  <div class="all-screen">
    <div class="save-modal">
      <h3 class="which-collection">In which collection would you like to save "<%= artwork.title %>"?</h3>
      <div>
        <% @tags.each do |tag| %>
        <%= link_to artwork_saved_artworks_path(artwork, {saved_artwork: {tag: tag}}), method: :post do %>
        <div class="collection-thumb d-flex">
          <% if current_user.saved_artworks_for(tag).last %>
          <div class="collection-image"><%= cl_image_tag current_user.saved_artworks_for(tag).last.photo, alt: "#" %></div>
          <% else %>
          <div class="collection-image"><i class="fas fa-palette"></i></div>
          <% end %>
          <div class="collection-tag-link">
            <p><%= tag %></p>
          </div>
        </div>
        <% end %>
        <% end %>
      </div>

      <h3 class="new-collection">New collection</h3>
      <div class="new-collection-form">
        <%= simple_form_for @saved_artwork, url: artwork_saved_artworks_path(artwork) do |f| %>
        <%= f.input :tag, label: false, placeholder: "New collection name" %>
        <%= f.submit "Create Collection", class: "btn-flat new-comment-btn" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_details-location-banner.html.erb
<%= cl_image_tag viewing_location.photo, alt: "#" %>

app/views/shared/_details-location.html.erb
<div class="container">
  <div class="details-head">
    <div class="headings">
      <div class="art-title"><%= @viewing_location.name %></div>
      <div class="artist-name"><%= @viewing_location.address %></div>
    </div>
    <div class="fave-save">
      <% if current_user.favorited?(@viewing_location) %>
        <%= link_to favorite_path, method: :delete do%>
          <div class="fave-save-icon"><i class="fas fa-heart" style="color: #F85961"></i></div>
        <% end %>
      <% else %>
        <%= link_to viewing_location_favorites_path(@viewing_location), method: :post do%>
          <div class="fave-save-icon"><i class="far fa-heart" style="color: black"></i></div>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="top-and-bottom-border">
    <div class="font-grey-to-black ">
      <p><strong> Description </strong></p>
    </div>
    <p> <%= @viewing_location.description %> </p>
  </div>
</div>

app/views/shared/_details.html.erb
<%= image_tag artwork.photo, alt: "#" %>
<div class="container">
  <div class="details-head">
    <div class="headings">
      <div class="art-title"><%= artwork.title %></div>
      <div class="artist-name"><%= artwork.artist.name %></div>
    </div>
    <div class="fave-save">
      <% if current_user.favorited?(artwork) %>
        <%= link_to favorite_path, method: :delete do %>
          <div class="fave-save-icon"><i class="fas fa-heart" style="color: #F85961"></i></div>
        <% end %>
      <% else %>
        <%= link_to artwork_favorites_path(artwork), method: :post do %>
          <div class="fave-save-icon"><i class="far fa-heart" style="color: black"></i></div>
        <% end %>
      <% end %>
      <% if current_user.saved?(artwork) %>
          <div class="fave-save-icon"><i class="fas fa-bookmark" style="color: #F85961"></i></div>
      <% else %>
          <div class="fave-save-icon"><i class="far fa-bookmark" style="color: black"></i></div>
      <% end %>
    </div>
  </div>

  <div class="details-body">
    <div class="description">
      <p><%= artwork.date_of_creation %> </p>
      <p><%= artwork.viewing_location.name %></p>
      <p> This <%= artwork.category.downcase %> is <%= artwork.medium.downcase %> </p>
    </div>

  </div>

</div>
<div class="all-screen">
  <div class="save-modal">
    <h3 class="which-collection">In which collection would you like to save "<%= artwork.title %>"?</h3>
    <div>
      <% @tags.each do |tag| %>
        <%= link_to artwork_saved_artworks_path(artwork, {saved_artwork: {tag: tag}}), method: :post do %>
          <div class="collection-thumb d-flex">
            <div class="collection-image"><%= image_tag current_user.saved_artworks_for(tag).last.photo, alt: "#" %></div>
            <div class="collection-tag-link">
              <p><%= tag %></p>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>

    <h3 class="new-collection">New collection</h3>
    <div class="new-collection-form">
      <%= simple_form_for @saved_artwork, url: artwork_saved_artworks_path(artwork) do |f| %>
        <%= f.input :tag, label: false, placeholder: "New collection name" %>
        <%= f.submit "Create Collection", class: "btn-flat new-comment-btn" %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_map.html.erb
<div
  id="map"
  style="width: 100%; height: 600px;"
  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-light bg-light">
  <div class="navbar-content">
    <% unless current_page?("/") %>
      <div style="padding-left: 14px;"><%= link_to artworks_path, :class=>"btn-back" do%><i class="fas fa-chevron-left"></i><% end %></div>
    <% else %>
      <div style="width: 38px;"></div>
    <% end %>
    <div class="logo">
      <%= link_to image_tag("artbeat-logo.png"), root_path %>
    </div>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>

  <div class="container">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Profile", user_path(current_user.id), class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Image search", new_artwork_path(current_user.id), class: "nav-link" %>
        </li>
        <li class="nav-item-log-in-out">
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
        <% else %>
        <li class="nav-item-log-in-out">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_search.html.erb
<!-- <form novalidate="novalidate" class="simple_form search" action="/artworks" accept-charset="UTF-8" method="get"><input name="utf8" type="hidden" value="&#x2713;" />
  <div class="search-flex">

    <div class="search-form-control form-group">
      <input class="form-control string required" type="text" name="search" id="search_query" placeholder="Search" />
    </div>

    <div class="search-button">
      <button name="button" type="submit" class="btn btn-flat">
        <i class="fas fa-search"></i>
      </button>
    </div>

  </div>
</form> -->

<form novalidate="novalidate" class="simple_form search" action="/artworks" accept-charset="UTF-8" method="get"><input name="utf8" type="hidden" value="&#x2713;" />
  <div class="search-form-control form-group mt-4 mb-0">
    <input class="form-control string required" type="text" name="search" id="search_query" placeholder="Search by location" />
    <button name="button" type="submit" class="btn btn-flat">
      <i class="fas fa-search"></i>
    </button>
  </div>
</form>